### ISSUE TITLE
Is it possible to get a 3D model with neutral pose?

### ISSUE THREAD

**Issue by g-ch** [runa91/bite_release#1]
Thank you very much for releasing the code of the excellent work! 

Can I get the neutral-pose mesh? For example, I have an image of a French Bulldog sitting. By running the code I can get a 3D mesh of the dog sitting as the image shows. But I want a mesh of the dog standing, i.e., remove the pose transformations. Could you let me know if it's possible? If possible, how can I do that?

**Comment by g-ch** [comment]
I found a way to get the neutral pose. Feeding a neutral rotation matrix to the SMAL model to generate the mesh works.

**Comment by 1192267986** [comment]
Hello, where did this neutral matrix come from, 
smal_verts, keyp_3d, _ = smal(beta=optimed_betas, betas_limbs=optimed_betas_limbs, pose=optimed_pose_with_glob,  vert_off_compact=optimed_vert_off_compact, trans=optimed_trans, keyp_conf='olive', get_skin=True)

Do we assign this pose to a 0 matrix
